# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [commit, push]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: sbt-scalafmt
        name: scalafmt
        language: system
        always_run: true
        pass_filenames: false
        verbose: false
        entry: sbt
        args: ["scalafmtAll"]
