name: "bImage"
on:
  push:
    branches:
      - main
      - dev
      - githactions
  pull_request:
    branches:
      - main
      - dev
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix build ".#dockerImage"
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME}}
        password: ${{ secrets.DOCKER_PASSWORD}}
    - name: push docker image to DockerHub
      run: |
        docker load < result
        docker push latest



  

