name: "bImage"
on:
  pull_request:
    -main
    -dev
  push:
    -main
    -dev
    -githactions
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - run: nix-build
    - run: nix-shell --run "echo OK"

